version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-project-1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - react-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=react-project-1"

networks:
  react-network:
    driver: bridge

volumes:
  nginx_logs:
    driver: local 